### PR TITLE
WIP: EXPRESS course clean up

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
*As per https://github.com/expresslang/expresslang.org/issues/18*

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 the "begin/end notes" identify what were originally lecturer notes. We need to convert them into real content that can be read before removing those markings. Can you help do that?

**Comment by manuel489** [comment]
> @manuel489 the "begin/end notes" identify what were originally lecturer notes. We need to convert them into real content that can be read before removing those markings. Can you help do that?

@ronaldtse 
* Each lecturer note contains a section title that is repeated afterwards. 
  I assume that we need to remove this repetition.
* For some sections, it makes more sense to me to interchange the position of some paragraphs.
  But that would mess with the lecturer notes, so I won't do it.

**Comment by ronaldtse** [comment]
@manuelfuenmayor is this ready?

**Comment by manuelfuenmayor** [comment]
> @manuelfuenmayor is this ready?

Not yet @ronaldtse, sorry. I have resumed my work.

**Comment by ronaldtse** [comment]
Finally merged. Thanks!

**Pull request merged**
